### ISSUE TITLE
0.19.0 breaking change

### ISSUE THREAD

**Issue by tkukushkin** [drgarcia1986/simple-settings#111]
Hello! We use custom dynamic settings backend and specify it by:
```python
SIMPLE_SETTINGS = {
    'DYNAMIC_SETTINGS': {
        'backend': 'some_package.http_settings_reader',
    }
}
```
After updating to 0.19.0 we get exception `simple_settings.dynamic_settings.InvalidDynamicSettingsReaderPath: The path of dynamic settings reader [some_package.http_settings_reader] is invalid`

Maybe need to do major version update for this breaking change?

**Comment by drgarcia1986** [comment]
Oh sorry @tkukushkin sorry about that 😞 
I just change the dynamic settings reader load mechanism to get the full classpath in [PR 90](https://github.com/drgarcia1986/simple-settings/pull/90) and totally forgot to up major version, sorry. 
I'll create a bugfix to load class in both ways and I'll add a warning about deprecated way.

Thank you

**Comment by drgarcia1986** [comment]
hi @tkukushkin thanks a lot, I just released version [0.19.1](https://pypi.org/project/simple-settings/0.19.1/) with a temporary fix, could you check if that version solves your problem? Also, for the next major version, I'll drop support to auto infer reader class name, and you'll need to add full class path on dynamic settings configuration, f.ex:

```python
SIMPLE_SETTINGS = {
    'DYNAMIC_SETTINGS': {
        'backend': 'some_package.http_settings_reader.Reader',
    }
}
```

**Comment by tkukushkin** [comment]
Oh, thanks! God fix, it solves my problem. 👍

**Comment by drgarcia1986** [comment]
you're welcome 😄
