### ISSUE TITLE
Imported modules on settings

### ISSUE THREAD

**Issue by lucascosta** [drgarcia1986/simple-settings#14]
Modules imported inside the settings files are being included into the `settings` object.
This can lead to problems in `deepcopy` operations in `as_dict` method.

**Comment by drgarcia1986** [comment]
Thank you for the feedback bro.
To solve this issue I chose ignoring imported modules in settings files.
I think it's the simplest way.

I will make a hotfix release in next hours
Let me know if something goes wrong.

**Comment by lucascosta** [comment]
Sweet man! Totally works!

**Comment by drgarcia1986** [comment]
YEAH!!! :tada: :smile:
