### ISSUE TITLE
How can I recompute dependant values?

### ISSUE THREAD

**Issue by SergeyPiskunov** [drgarcia1986/simple-settings#144]
Hi, folks!

For the given settings.py file:

NAME = "Alice"
MESSAGE = "Hello, " + NAME

Is it possible to achieve results listed below?

from simple_settings import settings

assert settings.MESSAGE == "Hello, Alice"
settings.NAME = "Bob"
assert settings.MESSAGE == "Hello, Bob"  # This currently fails

**Comment by drgarcia1986** [comment]
Hi @SergeyPiskunov thank you for use simple-settings.
Unfortunately no, settings will be evaluated on the first time you access some attribute on `settings` object. You can "[configure](https://github.com/drgarcia1986/simple-settings#configure)" value for some setting, but not a "hot calculate", f.ex:
```python
NAME = "Alice"
....
from simple_settings import settings

assert settings.NAME == "Alice"
settings.configure(NAME="Diego")
assert settings.NAME == "Diego"
```
Or maybe you can use [dynamic settings](https://github.com/drgarcia1986/simple-settings#dynamic-settings)

**Comment by SergeyPiskunov** [comment]
Ok, thank you for the reply.
