### ISSUE TITLE
Using variables on decorator methods

### ISSUE THREAD

**Issue by rafa-acioly** [drgarcia1986/simple-settings#148]
i'm trying to write a test to test a `decorator` and the value that i mock with `settings_stub` is not working when i call the variable on the decorator method.

### The config.
```py
MY_VAR = 3
```

### The test:

```py
with settings_stub(MY_VAR=0):
    function_call()
```

### The code

```py
from simple_settings import settings

def retry(retries=3):
    """decorator exemplo"""
    pass


def function_call():
    # if i print settings.MY_VAR i see "0"
    return another_function()


# inside the retry method the retries param is 3 (the default)
@retry(retries=settings.MY_VAR)
def another_function():
    pass
```

Is this a well know situation? i'm missing something?

**Comment by drgarcia1986** [comment]
Hi @rafa-acioly the trouble is, python will evaluate the value of argument `retries` on the first time the module with function was imported, f.ex:
```python
>>> def my_func(arg=[]):
...     print(id(arg))
...
>>> my_func()
4304321024
>>> my_func()
4304321024
>>> my_func()
4304321024
>>> my_func({})
4303260032
>>> my_func()
4304321024
```
It's a known python behavior

**Comment by rafa-acioly** [comment]
Got it, thanks.
