### ISSUE TITLE
Add topic: settings

### ISSUE THREAD

**Issue by maroux** [drgarcia1986/simple-settings#187]
Just came across this library while looking for a solution for settings in plain python (non-django / non-flask) and it looks good, however, you are missing topics in your settings so the library isn't shown in searches such as [this one](https://github.com/topics/settings?l=python&o=desc&s=). You might want to consider adding some topics (look at [dynaconf](https://github.com/rochacbruno/dynaconf)) for inspiration 😉..

**Comment by drgarcia1986** [comment]
Thank you @maroux 
![image](https://user-images.githubusercontent.com/5291018/94851474-e1373400-03fe-11eb-8248-c5eee9e2bb71.png)
just for the sake of curiosity take a look at issue #5 of simple-settings 😄
