### ISSUE TITLE
`distutils` is deprecated. `distutils.util.strtobool` needs replacement.

### ISSUE THREAD

**Issue by leorochael** [drgarcia1986/simple-settings#273]
As of Python 3.10, distutils has been deprecated, which results in this `DeprecationWarning` when using simple_settings:

```
lib/python3.10/site-packages/simple_settings/special_settings.py:5: DeprecationWarning: The distutils package is deprecated and slated for removal in Python 3.12. Use setuptools or check PEP 632 for potential alternatives
    from distutils.util import strtobool
```

To eliminate this warning, PEP 632 recomends copying the implementation into your own code, or reimplementing:

https://www.python.org/dev/peps/pep-0632/#migration-advice

An alternative is to use str2bool from PyPI:

https://github.com/symonsoft/str2bool

**Comment by drgarcia1986** [comment]
Thank you @leorochael 
I removed distutils on #281
