### ISSUE TITLE
Settings inheritance

### ISSUE THREAD

**Issue by rochacbruno** [drgarcia1986/simple-settings#5]
# problem

I would like to have multiple settings files to use according to the environment 'test_settings', 'prod_settings', 'amazon_settings', 'openshift_settings' etc... but I would like the ability to mix then

Currently I can use the worst solution ever

```python
try:
    from local_settings import *
except ImportError:
    pass
```

But, it is usual to avoid using "imports" inside settings file, that kind of file should be a simple repository of **KEY:value**, besides that, there is the fact that the hierarchy order can change between environments.

# solution

So in order to do have this I propose this **SSEP** (Simple Settings Enhancement Proposal) LOL

having 3 settings files in project 

    settings.py
    test_settings.cfg
    vendor/amazon_settings.py

```bash
python myproject.py --settings=settings,test_settings.cfg,vendor/amazon_settings.py
```

1. can accept only the name of settings module, without the need to specify the file extensions
2. Settings can reside in **.py** or in **.cfg** files
3. can accept full directory path
4. Load the settings in the specified order, overriding the conflicted keys (dict.update automatically does that)

# caveats

Maybe it is not simple settings anymore! LOL

**Comment by drgarcia1986** [comment]
![challenge accepted](https://31.media.tumblr.com/a8ce1eb38b6f6293776dffc0ad8ca674/tumblr_inline_mzrzbofe0v1rbmqgm.jpg)

Great proposal :+1: 

Currently you can specify the settings file in the path of your package.
For example, with a struct like this:
```
└── settings
    ├── base.py
    ├── development.py
    ├── __init__.py
    └── vendor
        ├── amazon.py
        └── __init__.py
```
You can load `amazon` setting with this parameter: `--settings=settings.vendor.amazon`.

I think `cfg` files (with _key:value_ settings) is not a big problem, maybe the big challenge here is the `pipeline`, but, if it's is usefull for someone, is a good a idea :smile: .

For users, still a `simple-settings` but, after this improvement, I can update project description to `A badass settings manager with a simple interface` :joy:

**Comment by drgarcia1986** [comment]
@rochacbruno I'm started development of these features. 
I will do for steps, starting by [pipeline](https://github.com/drgarcia1986/simple-settings/tree/load-settings-pipeline) :+1:

**Comment by drgarcia1986** [comment]
I will close this issue, I believe the challenge already completed, thanks for proposal :smile:
