### ISSUE TITLE
handling secret settings

### ISSUE THREAD

**Issue by sobolevn** [drgarcia1986/simple-settings#54]
Hi, thanks for the lib!

What it the best practice to handle the secret settings? Overriding values with the `env` vars?
Should it be in the docs somewhere?

**Comment by drgarcia1986** [comment]
Hi @sobolevn , thanks for feedback?

What kind of secret settings? databases or AWS credentials for example?
You can do it with two ways, with environment variables or config files placed on the host.

With environment, you can activate `OVERRIDE_BY_ENV` [special setting](http://simple-settings.readthedocs.io/en/latest/#special-settings), for instance:

```python
SIMPLE_SETTINGS = {'OVERRIDE_BY_ENV': True}

MY_SECRET = ''
```

and, do something like this:
```
export MY_SECRET="some really secret"

**Comment by drgarcia1986** [comment]
Hi @sobolevn, thanks for your feedback!

What kind of secret settings? databases or AWS credentials for example?
You can do it with two ways, with environment variables or config files placed on the host.

With environment, you can activate `OVERRIDE_BY_ENV` [special setting](http://simple-settings.readthedocs.io/en/latest/#special-settings), for instance:

```python
# settings.py
SIMPLE_SETTINGS = {'OVERRIDE_BY_ENV': True}
MY_SECRET = ''
```

and, do something like this:
```
$ export MY_SECRET="some really secret"
$ python my_app.py --simple-settings=settings
```
The simple-settings override the value of `MY_SECRET` with value of environment variable

With config files, you can create a simple KEY=VALUE file (or json or yaml) with your secrets and use this file in the simple-settings [load pipeline](http://simple-settings.readthedocs.io/en/latest/#load-multiple-settings-modules), for instance:

```
# secrets.cfg
MY_SECRET=some really secret
```
```
$ python my_app.py --settings-settings=settings,secrets.cfg
```

let me know if this works for you.

**Comment by sobolevn** [comment]
Works perfectly fine. Thanks!

```bash
python app.py --settings=config.development,config/secret.cfg
```
