### ISSUE TITLE
support logging configuration

### ISSUE THREAD

**Issue by guihaojin** [drgarcia1986/simple-settings#55]
Thanks for building simple-settings and it's very helpful for my project.

I am wondering if you ever considered support logging configuration like Django settings.

**Comment by drgarcia1986** [comment]
Thank you @guihaojin 

For sure, it's a great idea.
I'll work on it in next days

**Comment by drgarcia1986** [comment]
@guihaojin done, update simple-settings to 0.11 and check `configure_logging` [special setting](http://simple-settings.readthedocs.io/en/master/#special-settings) to know how that works.

I'm waiting for your feedback :smile:

**Comment by guihaojin** [comment]
Thank you @drgarcia1986 , I will take a look!

**Comment by guihaojin** [comment]
Looks great, thanks!

**Comment by drgarcia1986** [comment]
Awesome!
