### ISSUE TITLE
Dynamic settings: there is no way to return None, False, 0, empty string

### ISSUE THREAD

**Issue by unknownlighter** [drgarcia1986/simple-settings#68]
```
if self._dynamic_reader:
    dynamic_result = self._dynamic_reader.get(attr)
    if dynamic_result:
        self._dict[attr] = dynamic_result
        result = dynamic_result
```
This code does not allow to return from dynamic_reader value that doesn't meet the condition `if self._dynamic_reader:` such as `None`, `False`, `0`, `''`

**Comment by unknownlighter** [comment]
I suggest that _dynamic_reader should raise AttributeError if attr not found. Then
```
if self._dynamic_reader:
    try:
    	dynamic_result = self._dynamic_reader.get(attr)
    except AttributeError:
    	pass
    else:
        self._dict[attr] = dynamic_result
        result = dynamic_result

```

**Comment by drgarcia1986** [comment]
makes sense, how do you think about handle this behavior (raise AttributeError) on dynamic_settings backends (e.g. Redis)?

**Comment by drgarcia1986** [comment]
to begin we can check if `result` is diferent of `None` and not a "non zero" value, e.g.:
```python
if self._dynamic_reader:
    dynamic_result = self._dynamic_reader.get(attr)
    if dynamic_result is not None:  # <---
        self._dict[attr] = dynamic_result
        result = dynamic_result
```
This change fix issues with `0`, `''` and `False`, what do you think @unknownlighter ?

**Comment by unknownlighter** [comment]
python redis client has a different behavior for cases when key was not found and when key has None value:
```
>>> import redis
>>> r = redis.StrictRedis()
>>> r.get('foo')
>>> r.set('foo', None)
True
>>> r.get('foo')
b'None'
```
so we can raise AttributeError when redis returned None and return None when redis returned b'None'

**Comment by unknownlighter** [comment]
Anyway, check for None value (`if dynamic_result is not None:`) much better than current behavior

**Comment by drgarcia1986** [comment]
Great, I'll work on it!

**Comment by drgarcia1986** [comment]
Thank you @unknownlighter for your feedback, I'll release a hotfix soon.

**Comment by unknownlighter** [comment]
Great. Thank you @drgarcia1986 for fast response and fix
