### ISSUE TITLE
Notice about special settings deprecated

### ISSUE THREAD

**Issue by JonathanHuot** [drgarcia1986/simple-settings#72]
Hi,

I would like to note that you can set special settings using JSON settings, and not only python, as mentioned in documentation: 

> Note: special settings may only be specified in python settings files (not ini, yaml, etc.).

For instance, you can enable it by using:

app.py: 

```
from simple_settings import settings
print(settings.SIMPLE_CONF)
```

project_json.json
```
{
    "SIMPLE_SETTINGS": {
        "OVERRIDE_BY_ENV": true
    },
    "SIMPLE_CONF": "simple"
}
```

Run command: 
```
$ export SIMPLE_SETTINGS=project_json
$ python app.py
simple
$ export SIMPLE_CONF=yohman
$ python app.py
yohman
```

**Comment by drgarcia1986** [comment]
You're right, thank you.
Also, I think that works with YAML too.

What do you think about open a PR fixing docs?
