### ISSUE TITLE
Special types cannot be overriden by ENV.

### ISSUE THREAD

**Issue by JonathanHuot** [drgarcia1986/simple-settings#73]
If we use any special types (dict, list, number, boolean) in configuration, we cannot override it by environment, else we lose the special type.

E.g. with a settings below:
```
{
    "SIMPLE_SETTINGS": {
        "OVERRIDE_BY_ENV": true
    },
    "BOOL": true,
    "DICT": {
        "key": "value"
    },
    "LIST": [1, 2]
}
```

And with python code as below:
```
from simple_settings import settings

print(settings.BOOL)
print("Test Passed {}".format(settings.BOOL is True))

print(settings.DICT)
print("Test Passed {}".format(isinstance(settings.DICT, dict)))

print(settings.LIST)
print("Test Passed {}".format(len(settings.LIST) == 2))
```

If we use the settings file as-is, we got all tests passed :+1: 
```
$ python app.py
True
Passed True
{'key': 'value'}
Passed True
[1, 2]
Passed True
```

But then, if we try to override one of them, all tests failed :-1: 
```
$ BOOL=True DICT="{'key': 'value'}" LIST="[1, 2]" python app.py 
True
Passed False
{'key': 'value'}
Passed False
[1, 2]
Passed False
```

I think `simple-settings` should convert environment variables depending the settings format (JSON, YAML, ..) into native python types. e.g. using `json.loads()` on os.environ when using a JSON settings file.

**Comment by drgarcia1986** [comment]
Hm, good idea, maybe we can use [jsonpickle](https://jsonpickle.github.io) like is used in dynamic settings, what do you think about it?

**Comment by JonathanHuot** [comment]
Yes, it makes sense to have more flexibility than `json.loads` and also repick a library used elsewhere in the project.

**Comment by drgarcia1986** [comment]
Hi @JonathanHuot there's a way, using [REQUIRED_SETTINGS_TYPES](https://github.com/drgarcia1986/simple-settings#required-settings-types), f.ex:
```python
# project_settings.py

SIMPLE_SETTINGS = {
    'OVERRIDE_BY_ENV': True,
    'REQUIRED_SETTINGS_TYPES': {
        'BOOL': 'bool',
        'DICT': 'json.loads',
        'LIST': 'json.loads'
    }
}
BOOL = True
DICT = {'key': 'value'}
LIST = [1, 2]
```
```python
# app.py
import os

from simple_settings import settings

os.environ.setdefault('SIMPLE_SETTINGS', 'project_settings')

print(settings.BOOL)
print("Test Passed {}".format(settings.BOOL is True))

print(settings.DICT)
print("Test Passed {}".format(isinstance(settings.DICT, dict)))

print(settings.LIST)
print("Test Passed {}".format(len(settings.LIST) == 2))
```
Running with env override:
```shell
$ python app.py
True
Test Passed True
{'key': 'value'}
Test Passed True
[1, 2]
Test Passed True
```
Now with env:
```
$ BOOL=true DICT='{"new_key": "new_value"}' LIST='[3, 4]' python app.py
True
Test Passed True
{'new_key': 'new_value'}
Test Passed True
[3, 4]
Test Passed True
```

I hope this helps you!
Thank you for the report.
