### ISSUE TITLE
Using default settings

### ISSUE THREAD

**Issue by zivSher** [drgarcia1986/simple-settings#78]
Hi,
I've started using simple-settings for pytest tests.
I'm doing it by sending the --settings parameter in the command line, for example:

`pytest test_items.py --settings=settings.dev`

In order for that to be supported I added this to 'conftest.py':

`parser.addoption(
        '--settings', action='store'
    )`

Now, I wanted to use default settings so I won't need to send the '--settings' parameter every time, so I updated the 'conftest.pt' as follows:

`parser.addoption(
        '--settings', action='store', default="settings.dev"
    )`

But seems like it doesn't work. When trying to run the test I'm getting - 

`<[RuntimeError("Settings are not configured") raised in repr()] LazySettings object at 0x10fb54ef0>`

Is there an option to use this kind of default settings?
If I could set the settings file from the 'conftest.pt' I guess that would work.

Thanks.

**Comment by zivSher** [comment]
Looks like that will do 👍 
Thanks!

**Comment by drgarcia1986** [comment]
You're welcome 👍
